### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by joeaaron** [naokishibuya/car-finding-lane-lines#1]

**Comment by joeaaron** [comment]
cv2.line<line_image, *line, color, thickness>
only named arguments may follow *expression

**Comment by TheRochVoices** [comment]
This project is written in python3. You won't get the error if you're using python3.
If you still want to proceed with python2.7, refer to the link below:

http://answers.opencv.org/question/178246/how-to-solve-this-problem-syntaxerror-only-named-arguments-may-follow-expression/

**Comment by joeaaron** [comment]
thank you so much

**Comment by TheRochVoices** [comment]
You can close the issue now.
